language: scala
scala:
  - 2.12.7

env:
  - DISPLAY=:99.0

before_install:
  - sh -e /etc/init.d/xvfb start
  - sleep 3

script:
  - export DISPLAY=:0.0
  - sbt clean coverage test coverageReport

after_success:
  - sbt coverageReport coveralls